
import {
  BetweenHorizonalEnd,
  BetweenHorizonalStart,
  BetweenVerticalEnd,
  BetweenVerticalStart,
  Bold,
  BookMarked,
  ChevronDown,
  ChevronUp,
  ChevronsUpDown,
  Clipboard,
  Code,
  CodeXml,
  Columns2,
  Columns3,
  Columns4,
  Copy,
  CropIcon,
  Eraser,
  Eye,
  FlipHorizontal,
  FlipVertical,
  Frame,
  GripVertical,
  Pilcrow,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  ImageUp,
  IndentDecrease,
  IndentIncrease,
  Italic,
  Link,
  List,
  ListOrdered,
  ListTodo,
  LoaderCircle,
  Maximize,
  Minimize,
  Minus,
  PaintRoller,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pencil,
  Plus,
  Quote,
  Redo2,
  Replace,
  Settings,
  Sigma,
  SmilePlus,
  SmilePlusIcon,
  Sparkles,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCellsMerge,
  TableCellsSplit,
  Trash,
  Trash2,
  Type,
  Underline,
  Undo2,
  Unlink,
  Video,
  ZoomIn,
  ZoomOut,
  PencilRuler,
  WrapText,
  Loader2 as Loader,
  X,
  ExternalLink,
  NotebookPen
} from 'lucide-react';




import { AlignRightIcon } from './align-right-icon';
import { AlignJustifyIcon } from './align-justify-icon';
import { AlignLeftIcon } from './align-left-icon';
import { AlignCenterIcon } from './align-center-icon';
import { CodeBlockIcon } from './code-block-icon';
import { ColumnAddLeftIcon } from './column-add-left-icon';
import { ColumnAddRightIcon } from './column-add-right-icon';
import { LineHeightIcon } from './line-height-icon';
import { BlockquoteLeftIcon } from './blockquote-left-icon';
import { MenuDownIcon } from './menu-down-icon';
import { SizeLIcon } from './size-l-icon';
import { SizeMIcon } from './size-m-icon';
import { SizeSIcon } from './size-s-icon';
import {  AspectRatioIcon } from './aspect-ratio-icon';
import { DeleteColumnIcon } from './delete-column-icon';
import { DeleteRowIcon } from './delete-row-icon';

export const icons = {
  Bold,
  LoaderCircle,
  Italic,
  Underline,
  Quote,
  TextQuote: BlockquoteLeftIcon,
  Strikethrough,
  Minus,
  Eraser,
  PaintRoller,
  Redo2,
  Undo2,
  AlignCenter: AlignCenterIcon,
  AlignJustify: AlignJustifyIcon,
  AlignLeft: AlignLeftIcon,
  AlignRight: AlignRightIcon,
  ChevronDown,
  Subscript,
  Superscript,
  Code,
  Code2: CodeXml,
  Type,
  IndentIncrease,
  IndentDecrease,
  List,
  ListOrdered,
  ListTodo,
  Link,
  ImageUp,
  Video,
  Maximize,
  Minimize,
  Table,
  Sparkles,
  Pencil,
  Unlink,
  BetweenHorizonalEnd,
  BetweenHorizonalStart,
  BetweenVerticalStart,
  BetweenVerticalEnd,
  TableCellsMerge,
  TableCellsSplit,
  Trash2,
  Trash,
  Replace,
  ChevronsUpDown,
  LineHeight: LineHeightIcon,
//   Word: FileWordOutline,
  HeadingParagraph: Pilcrow,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Columns2,
  Columns3,
  Columns4,
  Plus,
  Grip: GripVertical,
  Copy,
  Clipboard,
  PanelLeft,
  PanelRight,
  Columns: Columns2,
  Iframe: Frame,

  MenuDown:MenuDownIcon,
  SizeS: SizeSIcon,
  SizeM: SizeMIcon,
  SizeL: SizeLIcon,
  AspectRatio:AspectRatioIcon,

  Emoji: SmilePlus,

  DeleteColumn:DeleteColumnIcon,
  DeleteRow:DeleteRowIcon,
  SearchAndReplace: Replace,
  EmojiIcon: SmilePlusIcon,
  KatexIcon: Sigma,

  ColumnAddLeft: ColumnAddLeftIcon,
  ColumnAddRight: ColumnAddRightIcon,
  BookMarked,
  ZoomIn,
  ZoomOut,
  Settings,
  Eye,

//   TextDirection: Direction,
//   LeftToRight,
//   RightToLeft,

  Attachment: Paperclip,
//   GifIcon,
  ChevronUp,
  Crop: CropIcon,
//   Mermaid,
//   Twitter,
  CodeView:CodeBlockIcon,
  FlipX: FlipVertical,
  FlipY: FlipHorizontal,
  PencilRuler,
  WrapText,
  Loader,
  X,
//   Html,
  ExternalLink,
  Callout: NotebookPen
} as any;
